swagger: "2.0"
info:
  title: "api"
  version: "0.0.1-SNAPSHOT"
# host: "localhost:8080"
basePath: /api/v1
schemes:
  - http
consumes:
  - "application/json"
produces:
  - "application/json"
tags:
  - name: System
    description: "システム共通機能"
paths:
  /health:
    get:
      tags:
        - System
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/health"
definitions:
  health:
    type: string
    enum: [OK]
